
package com.netmind.ws.auth.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthWSImplService", targetNamespace = "http://ws.netmind.com/", wsdlLocation = "http://localhost:8080//AuthenticationWS/AuthWSImplService?wsdl")
public class AuthWSImplService
    extends Service
{

    private final static URL AUTHWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHWSIMPLSERVICE_EXCEPTION;
    private final static QName AUTHWSIMPLSERVICE_QNAME = new QName("http://ws.netmind.com/", "AuthWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080//AuthenticationWS/AuthWSImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHWSIMPLSERVICE_WSDL_LOCATION = url;
        AUTHWSIMPLSERVICE_EXCEPTION = e;
    }

    public AuthWSImplService() {
        super(__getWsdlLocation(), AUTHWSIMPLSERVICE_QNAME);
    }

    public AuthWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHWSIMPLSERVICE_QNAME, features);
    }

    public AuthWSImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHWSIMPLSERVICE_QNAME);
    }

    public AuthWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHWSIMPLSERVICE_QNAME, features);
    }

    public AuthWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthWS
     */
    @WebEndpoint(name = "AuthWSImplPort")
    public AuthWS getAuthWSImplPort() {
        return super.getPort(new QName("http://ws.netmind.com/", "AuthWSImplPort"), AuthWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthWS
     */
    @WebEndpoint(name = "AuthWSImplPort")
    public AuthWS getAuthWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.netmind.com/", "AuthWSImplPort"), AuthWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHWSIMPLSERVICE_EXCEPTION!= null) {
            throw AUTHWSIMPLSERVICE_EXCEPTION;
        }
        return AUTHWSIMPLSERVICE_WSDL_LOCATION;
    }

}
