/// <autosync enabled="true" />
/// <reference path="../AJAXBasico/AJAXJavaScript.js" />
/// <reference path="jquery-2.1.1.js" />
/// <reference path="jquery-ui-1.11.2.js" />
/// <reference path="modernizr-2.8.3.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/packages/jQuery.1.4.4/Content/Scripts/jquery-1.4.4.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/packages/jQuery.1.6.4/Content/Scripts/jquery-1.6.4.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/packages/jQuery.1.6.4/Tools/jquery-1.6.4-vsdoc-para.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/packages/jQuery.Validation.1.11.0/Content/Scripts/jquery.validate.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/packages/Microsoft.AspNet.SignalR.JS.1.0.1/content/Scripts/jquery.signalR-1.0.1.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/SignalR.Sample/SampleHub.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/SignalR.Sample/Silverlight.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/SignalR.Sample/Scripts/jquery-1.6.4.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/SignalR.Sample/Scripts/jquery.signalR-1.0.1.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/SignalR.Sample.SilverlightClient/Scripts/jquery-1.4.4.js" />
/// <reference path="../Web Sockets/SignalR.Sample/SignalR.Sample/SignalR.Sample.SilverlightClient/Scripts/jquery.validate.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/packages/jQuery.1.9.1/Content/Scripts/jquery-1.9.1.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/packages/jQuery.1.9.1/Tools/jquery-1.9.1.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/packages/jQuery.Color.2.1.2/Content/Scripts/jquery.color-2.1.2.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/packages/jQuery.Color.2.1.2/Content/Scripts/jquery.color.svg-names-2.1.2.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/packages/Microsoft.AspNet.SignalR.JS.1.1.3/content/Scripts/jquery.signalR-1.1.3.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/packages/Microsoft.AspNet.SignalR.Sample.1.1.2/content/SignalR.Sample/SignalR.StockTicker.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/SignalR3/Scripts/jquery-1.9.1.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/SignalR3/Scripts/jquery.color-2.1.2.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/SignalR3/Scripts/jquery.color.svg-names-2.1.2.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/SignalR3/Scripts/jquery.signalR-1.1.3.js" />
/// <reference path="../Web Sockets/SignalR3-Oficial/SignalR3/SignalR.Sample/SignalR.StockTicker.js" />
/// <reference path="../Web Sockets/SignalR_Demo1/packages/jQuery.1.8.2/Content/Scripts/jquery-1.8.2.js" />
/// <reference path="../Web Sockets/SignalR_Demo1/packages/jQuery.1.8.2/Tools/jquery-1.8.2.js" />
/// <reference path="../Web Sockets/SignalR_Demo1/packages/Microsoft.AspNet.SignalR.JS.1.0.0/content/Scripts/jquery.signalR-1.0.0.js" />
/// <reference path="../Web Sockets/SignalR_Demo1/SignalR_Demo1/Scripts/jquery-1.8.2.js" />
/// <reference path="../Web Sockets/SignalR_Demo1/SignalR_Demo1/Scripts/jquery.signalR-1.0.0.js" />
/// <reference path="../Web Sockets/SignalR_Demo___/packages/jQuery.1.8.2/Content/Scripts/jquery-1.8.2.js" />
/// <reference path="../Web Sockets/SignalR_Demo___/packages/jQuery.1.8.2/Tools/jquery-1.8.2.js" />
/// <reference path="../Web Sockets/SignalR_Demo___/packages/Microsoft.AspNet.SignalR.JS.1.0.0/content/Scripts/jquery.signalR-1.0.0.js" />
/// <reference path="../Web Sockets/SignalR_Demo___/SignalR_Demo1/Scripts/jquery-1.8.2.js" />
/// <reference path="../Web Sockets/SignalR_Demo___/SignalR_Demo1/Scripts/jquery.signalR-1.0.0.js" />
/// <reference path="../WebWorkers/citas.js" />
/// <reference path="../WebWorkers/gestorWorkers.js" />
/// <reference path="../WebWorkers/tarea.js" />
