
package com.netmind.ws.binary.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileServer", targetNamespace = "http://netmind.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FileServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    public byte[] downloadFile(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
